version: "3"
services:
  node-app:
    build: .
    volumes:
      - .:/app
    expose:
      - 5000
    command: yarn start
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    ports:
      - 80:80
networks:
  default:
    driver: bridge
    name: node-app
