version: "3"
services:
  node-app:
    build: .
    volumes:
      - .:/app
    command: yarn start
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app
    ports:
      - 4000:4000
# networks:
#   default:
#     driver: bridge
#     name: node-app
